*

!README.md
!pyproject.toml
!benchmarks/
!benchmarks/**
!rust/
!rust/**
!scripts/
!scripts/**
!src/
!src/**

**/.git/
**/.pytest_cache/
**/.ruff_cache/
**/__pycache__/
**/target/
src/image_similarity/_rust*.so
